# Standard Library
import os

# Environment variables for configuration
API_PREFIX = os.environ.get("API_PREFIX")
DOCUMENTS_BUCKET_NAME = os.environ.get("DOCUMENTS_BUCKET_NAME")
VECTOR_STORE_BUCKET_NAME = os.environ.get("VECTOR_STORE_BUCKET_NAME")
QUERY_CACHE_TABLE_NAME = os.environ.get("QUERY_CACHE_TABLE_NAME")
BEDROCK_EMBEDDING_MODEL_ID = os.environ.get("BEDROCK_EMBEDDING_MODEL_ID")
BEDROCK_TEXT_GENERATION_MODEL_ID = os.environ.get(
    "BEDROCK_TEXT_GENERATION_MODEL_ID"
)
HOME_IP_SSM_PARAMETER_NAME = os.environ.get("HOME_IP_SSM_PARAMETER_NAME")
DOCUMENTS_METADATA_TABLE_NAME = os.environ.get("DOCUMENTS_METADATA_TABLE_NAME")
USER_POOL_ID = os.environ.get("USER_POOL_ID")
USER_POOL_CLIENT_ID = os.environ.get("USER_POOL_CLIENT_ID")
